version: '3.8'

services:
  redis:
    image: redis:7.0.11-alpine
    container_name: Ecommerce_redis
    networks:
      - main_network
    volumes:
      - redis_data:/data
    ports:
      - "6379"
    restart: on-failure

  rabbitmq:
    image: rabbitmq:management
    container_name: Ecommerce_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: on-failure
    networks:
      - main_network

  db:
    image: postgres
    container_name: Ecommerce_db
    restart: on-failure
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - main_network

  pgadmin:
    container_name: Ecommerce_pgadmin
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
      - main_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: Ecommerce_backend
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app/
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - rabbitmq
      - db
    networks:
      - main_network

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: Ecommerce_celery
    command: celery --app=backend worker -l INFO -Q send_otp_email,send_confirmation_email,send_welcome_email,send_notification
    volumes:
      - ./backend:/app/
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - rabbitmq
      - backend
    networks:
      - main_network

  flower:
    image: mher/flower
    container_name: Ecommerce_flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
    networks:
      - main_network

  frontend:
    container_name: Ecommerce_frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: npm run dev
    environment:
      - API_URL=http://nginx:8000/
    networks:
      - main_network
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: Ecommerce_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
      - ./backend/static:/usr/share/nginx/html/static
      - ./backend/media:/usr/share/nginx/html/media
    depends_on:
      - backend
      - frontend
    networks:
      - main_network

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  main_network:
    driver: bridge