# Generated by Django 5.0.3 on 2024-12-25 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('pending_payment', 'Pending Payment')], default='pending_payment', max_length=100, verbose_name='Status')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is paid')),
                ('paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Paid')),
                ('paid_date', models.DateField(auto_now_add=True, null=True, verbose_name='Paid date')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='OfferCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150, verbose_name='Code')),
                ('discount_percentage', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Discount percentage')),
                ('inventory', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='inventory')),
                ('expiration_date', models.DateTimeField(verbose_name='Expiration Date')),
            ],
            options={
                'verbose_name': 'Offer Code',
                'verbose_name_plural': 'Offer Codes',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Count')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_first_name', models.CharField(max_length=200, verbose_name='Receiver first name')),
                ('receiver_last_name', models.CharField(max_length=200, verbose_name='Receiver last name')),
                ('receiver_phone', models.CharField(max_length=15, verbose_name='Receiver phone')),
                ('receiver_national_code', models.CharField(max_length=10, verbose_name='Receiver National code')),
                ('receiver_post_code', models.CharField(max_length=10, verbose_name='Receiver Post code')),
                ('receiver_address', models.TextField(verbose_name='Receiver address')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'verbose_name': 'User Address',
                'verbose_name_plural': 'Users Addresses',
            },
        ),
    ]
