# Generated by Django 5.1.6 on 2025-04-14 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='DeliveredOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Delivered Order',
                'verbose_name_plural': 'Delivered Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.cart',),
        ),
        migrations.CreateModel(
            name='OutForDeliveryOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Out For Delivery Order',
                'verbose_name_plural': 'Out For Delivery Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.cart',),
        ),
        migrations.CreateModel(
            name='PendingPaymentOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Payment Order',
                'verbose_name_plural': 'Pending Payment Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.cart',),
        ),
        migrations.CreateModel(
            name='ProcessingOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Processing Order',
                'verbose_name_plural': 'Processing Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.cart',),
        ),
        migrations.AddField(
            model_name='cart',
            name='offer_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.offercode', verbose_name='Offer Code'),
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.cart', verbose_name='Cart'),
        ),
        migrations.AddField(
            model_name='order',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productcolor', verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productsize', verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='cart',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.useraddress', verbose_name='Receiver address'),
        ),
    ]
