# Generated by Django 5.0.3 on 2025-02-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='Paid date'),
        ),
    ]
