# Generated by Django 5.0.3 on 2025-01-30 08:20

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_discount_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000000), django.core.validators.MinValueValidator(0)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='color_code',
            field=colorfield.fields.ColorField(default='#fff', image_field=None, max_length=25, samples=None, verbose_name='Color code'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='color_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Color name'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(max_length=100, unique=True, verbose_name='Size'),
        ),
    ]
