# Generated by Django 5.0.3 on 2025-01-13 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_slider_alter_sitesetting_copyright'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='github',
        ),
        migrations.AddField(
            model_name='contactus',
            name='full_name',
            field=models.CharField(default='yas', max_length=200, verbose_name='Full Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='telegram',
            field=models.URLField(blank=True, max_length=400, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid Telegram URL starting with https://t.me/', regex='^https://t\\.me/.*$')], verbose_name='Telegram'),
        ),
    ]
