# Generated by Django 5.0.3 on 2025-02-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_remove_sitesetting_site_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='site_main_title',
            field=models.TextField(default='sdsd', verbose_name='Site Main Title'),
            preserve_default=False,
        ),
    ]
